sonar.projectKey=guiddodg_playground-plaza
sonar.organization=guiddodg

sonar.projectName=Playground Plaza
sonar.projectVersion=0.1

# Solo analizamos nuestro código, no assets de Unity
sonar.sources=Assets/_Project/Scripts
sonar.exclusions=Assets/TutorialInfo/**,Library/**,Temp/**,Build/**

sonar.cs.file.suffixes=.cs
sonar.sourceEncoding=UTF-8
